### ISSUE TITLE
DNS config for explore.ipld.io

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipld-explorer#2]
I'd like to deploy this to `explorer.ipld.io` unless anyone has a better ideas for the domain.

**Comment by mikeal** [comment]
I like that domain name :)

**Comment by olizilla** [comment]
maybe just `explore` so `explore.ipld.io` ?

@VictorBjelkholm how do I persuade Jenkins to build and deploy this as an inter-web-site?

**Comment by VictorBjelkholm** [comment]
@olizilla we need to setup the initial dns records via dnsimple, it's a fairly manual process. I'll get to it soon. 

Just make the final confirmation on `explore` vs `explorer` :)

**Comment by olizilla** [comment]
Shorter is gooder!

Let's go for `explore.ipld.io`

**Comment by olizilla** [comment]
@VictorBjelkholm pls can has? Sorry to hassle, but I want to test things out before dweb

**Comment by VictorBjelkholm** [comment]
@olizilla sorry, didn't realize it was for dweb summit. On it.

**Comment by olizilla** [comment]
@VictorBjelkholm I've merged #7 with the updates to the Jenkinsfile, but the CI build is complaining about the zone explorer.ipld.io not existing. Did you set up `explore.ipld.io` or `explorer.ipld.io`?

```
+ ./dnslink-dnsimple explorer.ipld.io /ipfs/QmfVYBimnxJrPNDLcuZH6bjPkogiKxx7yycpo9ByrQ1nBG _dnslink

error in createRecord: POST https://api.dnsimple.com/v2/zones/explorer.ipld.io/records: 404 Not Found

script returned exit code 1
```

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%20Shipyard%2Fipld-explorer/detail/master/7/pipeline

**Comment by olizilla** [comment]
This is working. But the SSL cert is a wildcard for `.ipfs.io` not `.ipld.io`. I'll raise a new issue.

**Comment by olizilla** [comment]
See https://github.com/ipfs-shipyard/ipld-explorer/issues/11
