### ISSUE TITLE
Can't browse cid v1 objects

### ISSUE THREAD

**Issue by fiatjaf** [ipfs-shipyard/ipld-explorer#25]
https://explore.ipld.io/#/explore/QmatUfA3cSbtcum116DED69nReXX5bY3ZraqF93YGFAKwd is ok,
https://explore.ipld.io/#/explore/zdj7Whyj2b7Tv5VVd4vjqAr5TzM3rixo8xBSAzMuwSD5gjE7Z, which is the same object, gives me `"Path error:dag-pb multihash should match provided cid"`

**Comment by olizilla** [comment]
Thanks for reporting this @fiatjaf, I'll take a look.
