### ISSUE TITLE
Alias: exploreR.ipld.io to explore.ipld.io

### ISSUE THREAD

**Issue by hsanjuan** [ipfs-shipyard/ipld-explorer#28]
Just saying :)

**Comment by olizilla** [comment]
If we're going to support this, we'd want `explorer.ipld.io` to respond with an http 301 permanent redirect to explore.ipld.io as we don't really want to have multiple domains / ipns names for the same app... though maybe that's my centralising instinct kicking in...

@VictorBjelkholm is it possible to configure the jenkinsfile to update multiple domains?

**Comment by lidel** [comment]
IMO a static HTTP 301 `explorer.ipld.io` → `explore.ipld.io` should be enough, as a courtesy for people typing by hand :)

No need to maintain dnslink for both.

**Comment by jessicaschilling** [comment]
Closed via https://github.com/ipfs/infra/issues/499!
