### ISSUE TITLE
Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/ipld-explorer#46]
When storing a cbor dag node that has a property with an empty array I get the error: `Reduce of empty array with no initial value`.

I think the culprit is here: https://github.com/ipfs-shipyard/ipld-explorer-components/blob/821e84e6798f816100f7b241ad9a690698c1d41c/src/lib/normalise-dag-node.js#L92

We need to check if the array is not empty.

**Comment by satazor** [comment]
PR at https://github.com/ipfs-shipyard/ipld-explorer-components/pull/11

**Comment by olizilla** [comment]
Fixed in #11 - thanks!
