### ISSUE TITLE
Expand links to bottom

### ISSUE THREAD

**Issue by vmx** [ipfs-shipyard/ipld-explorer#53]
I have a lot of links, I would expect that the component listing the links would expand to the bottom of the screen and not stop in the middle (I zoomed out a bit to make it clearer).

![image](https://user-images.githubusercontent.com/42839/58804860-2123b680-8613-11e9-82bb-bd83532829a7.png)

**Comment by jessicaschilling** [comment]
This is actually an issue with one of the components in this repo: https://github.com/ipfs-shipyard/ipld-explorer-components

Will dig into it deeper over there.

**Comment by lidel** [comment]
Not yet (need to release component to npm tomorrow, and switch this repo and ipfs-webui to it)
