### ISSUE TITLE
Two permissions alerts appear upon visit to ipld explorer

### ISSUE THREAD

**Issue by ericronne** [ipfs-shipyard/ipld-explorer#54]
Upon my first visit to the [ipld explorer](https://explore.ipld.io/), i was greeted by these two — count ’em, two — identical pop-up alerts. 
 
![image](https://user-images.githubusercontent.com/9259185/73862535-4b61ef80-4804-11ea-8a80-a491b5ed9843.png)

osx chrome 79.0.3945.130

**Comment by lidel** [comment]
@ericronne I tried to reproduce this but was unable to (tested Chromium 78, 79, 80)
May be specific Chrome version / macOS build.

Does this happen every time?

**Comment by ericronne** [comment]
No it was only on first visit. Loads without any alert now, including in private mode.

**Comment by lidel** [comment]
Odd. Let's keep it open for now.
If someone else can reproduce, please comment in this issue.

**Comment by lidel** [comment]
Not relevant since  #60, we may reopen in the future, when `windows.ipfs` is back.
