### ISSUE TITLE
How to embed this into WebUI?

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipld-explorer#6]
At first I thought about just embedding the URL through an iframe. But that would cause some issues such as not taking advantage of global caching.

I think the best way to do it would be to export the bundle and the ExplorePage. The bundle would be a function that could receive an options object and it could have as an option the `basepath`.

But before that it would be better to create a repository with our common components and icons so we could easily reuse the code.

**Comment by olizilla** [comment]
This was done by sepearting the components from the web-app. See https://github.com/ipfs-shipyard/ipld-explorer-components
