### ISSUE TITLE
Git makes explorer unhappy

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs-shipyard/ipld-explorer#9]
Loading this: https://ipfs.io/ipfs/QmYJETQ15RAnKXoJxqpXzcvQ2DuQA35UHwJBTjTPCSs9Ky/#/explore/QmViWi5az9iiPzESM6ruHf84TcmHSAVQ2KQdNveoDH7eaY/refs/heads/master

(or traversing the graph to it from above) results in it getting pretty angry and not working (and spinning cpus)

**Comment by olizilla** [comment]
Looks like an error is getting smothered

from `js-cid`
errorMsg = "multihash length inconsistent: 0x1114dc23ffefcd2feaef8036fda45e949afd86aae5d7"

**Comment by olizilla** [comment]
```
Failed to parse CID 8mWaJHXieAVxxLagBpdaNWFEBKVWmMiE Error: multihash length inconsistent: 0x1114dc23ffefcd2feaef8036fda45e949afd86aae5d7
    at Function.validateCID (index.js:235)
```

**Comment by olizilla** [comment]
Goes a wrong 'un here

https://github.com/multiformats/js-multihash/blob/2ace8ba9af7a4cd9c33c9480bfe382bb774e3f7d/src/index.js#L90-L100

**Comment by olizilla** [comment]
We get the same error from the cid util, http://cid-utils.ipfs.team/#8mWaJHXieAVxxLagBpdaNWFEBKVWmMiE which isn't suprising as they both use `js-cid`

**Comment by olizilla** [comment]
@whyrusleeping i got to sleeps now, if you have a moment to adjudicate over whether js-multihash is bugsy, or `8mWaJHXieAVxxLagBpdaNWFEBKVWmMiE` is a wonky CID, then let me know and I'll get it fixed tomorrow.

**Comment by olizilla** [comment]
Ooh is it because I'm passing a raw git hash and asking it to be a cid, when it is not one.

**Comment by whyrusleeping** [comment]
@olizilla huh, it looks like go-ipfs doesnt like that hash either. cc @magik6k, whats up with that hash?

**Comment by whyrusleeping** [comment]
Oh right, it needs the 'z' prefix: `z8mWaJHXieAVxxLagBpdaNWFEBKVWmMiE`

**Comment by olizilla** [comment]
@whyrusleeping IPLD Explorer shouldn't panic'n'freak out in that case, but can you confirm that this is a rogue block with a wonky link, rather than a legit arrangement of things that it should be rendering.

**Comment by whyrusleeping** [comment]
@olizilla It does not appear to be a rogue block, if you look here: https://ipfs.io/api/v0/dag/get?arg=QmViWi5az9iiPzESM6ruHf84TcmHSAVQ2KQdNveoDH7eaY/refs/heads

You can see the 'z' multibase prefix is correctly applied

**Comment by olizilla** [comment]
ruh roh. I shall go digging.

**Comment by olizilla** [comment]
@whyrusleeping js-ipld-dag-pb assumes that the link value in a dag-pb link will be a multihash, not a cid: https://github.com/ipld/js-ipld-dag-pb/blob/70b0cd53148fa26dc3e75fe250c0f1ad8161a59e/src/dag-link/index.js#L8-L23

**Comment by olizilla** [comment]
I haven't tested it and I'm not super familiar with that code, but my guess is _that's a problem_

**Comment by olizilla** [comment]
More https://github.com/ipld/js-ipld-dag-pb/issues/79

**Comment by olizilla** [comment]
ERH MER GLERB! IT GIT!

![screenshot 2018-07-31 18 03 31](https://user-images.githubusercontent.com/58871/43474951-34ab1450-94ec-11e8-9852-7dc20e527990.png)
